### PR TITLE
add io.closer for reader

### PR DESCRIPTION
**Pull request by sinaw369**

### CODE REVIEW

**Comment by icza** [comment]
This one looks better, but again, I don't believe closing the source belongs to the back scanner's responsibility.

A resource should be closed by the entity that creates it. The source `io.ReaderAt` is NOT created by the `Scanner` (just passed to it via a constructor-like function), so `Scanner` should not be responsible for closing it.

The example code also follows this idiom: it creates a file, and closes it deferred, then passes it to `NewScanner()`. Again, if you need to do this many times, you may create a wrapper type or function that deals with closing the source file.

`Scanner` does not have a `Close()` method because it does not create any resources that needs closing.

**Comment by sinaw369** [comment]
> This one looks better, but again, I don't believe closing the source belongs to the back scanner's responsibility.
> 
> A resource should be closed by the entity that creates it. The source `io.ReaderAt` is NOT created by the `Scanner` (just passed to it via a constructor-like function), so `Scanner` should not be responsible for closing it.
> 
> The example code also follows this idiom: it creates a file, and closes it deferred, then passes it to `NewScanner()`. Again, if you need to do this many times, you may create a wrapper type or function that deals with closing the source file.
> 
> `Scanner` does not have a `Close()` method because it does not create any resources that needs closing.

Yes, that's correct. The code in question doesn't create any resources that require closing. However, in some cases, when you have a slice of a large file, you may need to close it once you reach the end of the file. I think it is more convenient to close the file with a backscanner. By the way, I'm a junior developer and I'm eager to learn from your expertise.

**Comment by icza** [comment]
Even you used the phrase "in some cases". Then in those "some cases" close the resource where it is created (or appropriate). But not in all cases should the resource be closed, so it's not (and should not be) incorporated in the scanner.

**Comment by sinaw369** [comment]
> Even you used the phrase "in some cases". Then in those "some cases" close the resource where it is created (or appropriate). But not in all cases should the resource be closed, so it's not (and should not be) incorporated in the scanner.

I understand, thank you for your response.

**Pull request closed without merging**
